#!/bin/bash
# by pax (pangxing@tp-link.net)

function x()
{
    echo "vim \`find ./ -name $1\`" > /home/$(whoami)/mybin/tmp/$1
    chmod 777 /home/$(whoami)/mybin/tmp/$1
    vim `find ./ -name $1`
}

function gx()
{
    echo "gvim \`find ./ -name $1\`" > /home/$(whoami)/mybin/tmp/$1
    chmod 777 /home/$(whoami)/mybin/tmp/$1
    gvim `find ./ -name $1`
}

function xfind()
{
    find . -name .repo -prune -o -name .git -prune -o -name "*$@*" -print
}

function xfindr()
{
    find . -name .repo -prune -o -name .git -prune -o -name "*$@*" -print
}

function vxfind()
{
    vim `find . -name .repo -prune -o -name .git -prune -o -name "*$@*" -print`
}

function xv()
{
    vim `find . -name .repo -prune -o -name .git -prune -o -name "*$@*" -print`
}

function xfindi()
{
    find . -name .repo -prune -o -name .git -prune -o -iname "*$@*" -print
}

function jgrep()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f -name "*\.java" -print0 | xargs -0 grep --color -n "$@"
}

function jgrepi()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f -name "*\.java" -print0 | xargs -0 grep -i --color -n "$@"
}

function cgrep()
{
    find . -name .repo -prune -o -name .git -prune -o -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 grep --color -n "$@"
}

function cgrepi()
{
    find . -name .repo -prune -o -name .git -prune -o -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 grep -i --color -n "$@"
}

function resgrep()
{
    for dir in `find . -name .repo -prune -o -name .git -prune -o -name res -type d`; do find $dir -type f -name '*\.xml' -print0 | xargs -0 grep --color -n "$@"; done;
}

function resgrepi()
{
    for dir in `find . -name .repo -prune -o -name .git -prune -o -name res -type d`; do find $dir -type f -name '*\.xml' -print0 | xargs -0 grep -i --color -n "$@"; done;
}

# Makefile
function mgrep()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f \( -name "Makefile*" -o -name '*.mk' \) -print0 | xargs -0 grep --color -n "$@"
}

function mgrepi()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f \( -name "Makefile*" -o -name '*.mk' \) -print0 | xargs -0 grep -i --color -n "$@"
}

# bb Makefile
function bbgrep()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f \( -name "*.bb" \) -print0 | xargs -0 grep --color -n "$@"
}

function bbgrepi()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f \( -name "*.bb" \) -print0 | xargs -0 grep -i --color -n "$@"
}

# pdf
function pgrep()
{
    find . -name '*.pdf' -print -exec pdftotext {} /tmp/tmp.txt \; -exec grep --color "$@" /tmp/tmp.txt \;
}

function pgrepi()
{
    find . -name '*.pdf' -print -exec pdftotext {} /tmp/tmp.txt \; -exec grep -i --color "$@" /tmp/tmp.txt \;
}

function xgrep()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f -name "*" -print0 | xargs -0 grep --color -n "$@"
}

function xgrepi()
{
    find . -name .repo -prune -o -name .git -prune -o  -type f -name "*" -print0 | xargs -0 grep -i --color -n "$@"| sed 's/:/ +/' |grep -i --color -n "$@"
}

function find-grep()
{
    find . -type f -name "$1" |xargs echo "PATH:"
    find . -type f -name "$1" |xargs grep --color -i -n "$2"
    #find . -name .repo -prune -o -name .git -prune -o  -type f -print0 -name "$1"|xargs -0 grep --color -i -Rs "$2" -n
}

function gitdiffst()
{
    echo git diff $@ --name-status 
    git diff $@ --name-status 
}

function autocd()
{
    install -d $1
    cd $1
}

