export opgcc=/home/xujiaxuan/smartRouter/qsdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
export  STAGING_DIR=/home/xujiaxuan/smartRouter/qsdk/staging_dir
server_:server_.o
	$(opgcc) server_.o -o	server_ 
server_.o:server_.c
	$(opgcc) -c server_.c
